Repository WildCodeSchool/orleans-0918-php-aslo, pull requests merged in 2018-10, with the labels that each got.

#2 S01 us1 navbar
  public/assets/css/styles.css
  src/View/Item/index.html.twig
  src/View/layout.html.twig
Labels: Reviewed by PO

#3 Dev__S01_US01_navbar
  public/assets/css/styles.css
  src/View/Item/index.html.twig
  src/View/layout.html.twig
Labels: Reviewed by PO

#8 Us12 1 structure html photos home
  composer.lock
  public/assets/css/styles.css
  public/assets/images/photo_galerie_1.png
  public/assets/images/photo_galerie_2.png
  public/assets/images/photo_galerie_3.png
  src/View/Item/galleryPhotosHome.html.twig
  src/View/Item/index.html.twig
Labels: Reviewed by PO

#4 Sprint01_UserStory03_banniere
  public/assets/css/styles.css
  public/assets/images/banniere.jpg
  src/View/Item/header.html.twig
  src/View/layout.html.twig
Labels: Reviewed by PO, correction done

#9 Dev to Master
  composer.lock
  public/assets/css/styles.css
  public/assets/images/banniere.jpg
  public/assets/images/photo_galerie_1.png
  public/assets/images/photo_galerie_2.png
  public/assets/images/photo_galerie_3.png
  src/View/Item/galleryPhotosHome.html.twig
  src/View/Item/header.html.twig
  src/View/Item/index.html.twig
  src/View/layout.html.twig
Labels: Reviewed by PO

#12 Us02 footer
  app/routing.php
  public/assets/css/styles.css
  public/assets/images/logo_aslo45.jpg
  public/assets/images/logo_wcs.png
  src/Controller/HomeController.php
  src/View/Home/index.html.twig
  src/View/footer.html.twig
  src/View/layout.html.twig
Labels: Reviewed by PO, correction done

#15 Dev
  app/routing.php
  public/assets/css/styles.css
  public/assets/images/logo_aslo45.jpg
  public/assets/images/logo_wcs.png
  src/Controller/HomeController.php
  src/View/Home/index.html.twig
  src/View/footer.html.twig
  src/View/layout.html.twig
Labels: Reviewed by PO

#16 S02 us04 qui sommes nous
  app/routing.php
  public/assets/css/styles.css
  public/assets/images/about_us.jpg
  src/View/Home/About_us.twig
  src/View/Home/index.html.twig
Labels: Reviewed by PO, correction done

#17 Dev
  app/routing.php
  public/assets/css/styles.css
  public/assets/images/about_us.jpg
  src/View/Home/About_us.twig
  src/View/Home/index.html.twig
  src/View/Home/video.html.twig
Labels: Reviewed by PO

#22 Fix us12
  src/View/Home/galleryPhotosHome.html.twig
  src/View/Home/index.html.twig
Labels: Reviewed by PO

#24 S02_US22_gallery
  app/routing.php
  public/assets/images/image5bc9971e6275a4.62562562.jpg
  public/assets/images/image5bc99a510edf41.33724827.jpg
  public/assets/images/image5bc99a511086f8.62492621.jpg
  public/assets/images/image5bc99a51118af8.61910824.jpg
  public/assets/images/image5bc99b58bf0a94.07565975.jpg
  public/assets/images/image5bc99b58c08843.66866385.jpg
  public/assets/images/image5bc99b58c16819.50295446.jpg
  public/assets/images/image5bc99b58c279a0.90679304.jpg
  public/assets/images/image5bc99de1c60694.48842372.jpg
  public/assets/images/image5bc99de1c7d345.28061929.jpg
  public/assets/images/image5bc9a02ce7bd30.00517429.jpg
  public/assets/images/image5bc9a2f276ce58.54652820.jpg
  src/Controller/PictureController.php
  src/Model/Picture.php
  src/Model/PictureManager.php
  src/View/Picture/index.html.twig
  src/View/header.html.twig
Labels: Reviewed by PO

#29 fix pour titre des photos sur le modal
  src/View/Picture/index.html.twig
Labels: Reviewed by PO

#23 S02 us10 contact form
  app/routing.php
  composer.json
  composer.lock
  public/assets/css/styles.css
  src/Controller/HomeController.php
  src/Controller/ItemController.php
  src/Filter/FilterInterface.php
  src/Filter/Text.php
  src/View/Home/contact_form.twig
  src/View/Home/index.html.twig
Labels: Reviewed by PO

#28 S3 us26 admin add event form
  .gitignore
  app/routing.php
  public/assets/css/admin.css
  public/assets/css/events.css
  public/assets/fonts/Starjedi.ttf
  public/assets/images/events/.gitkeep
  src/Controller/EventController.php
  src/Model/Event.php
  src/Model/EventManager.php
  src/View/Event/_form.html.twig
  src/View/Event/add.html.twig
  src/View/Event/events.html.twig
  src/View/Home/about_us.twig
  src/View/Home/index.html.twig
Labels: Reviewed by PO

#21 S02 us5 gymnase address section
  public/assets/css/styles.css
  src/Controller/HomeController.php
  src/Model/Address.php
  src/Model/AddressManager.php
  src/View/Home/GymnasiumAdressSection.html.twig
  src/View/Home/index.html.twig
Labels: changes requested

#42 S3 us17 formulaire inscription
  app/routing.php
  src/Controller/MemberController.php
  src/Model/Member.php
  src/Model/MemberManager.php
  src/View/Member/memberForm.html.twig
Labels: Reviewed by PO

#45 Dev
  .gitignore
  app/routing.php
  composer.lock
  public/assets/css/admin.css
  public/assets/css/events.css
  public/assets/css/styles.css
  public/assets/fonts/Starjedi.ttf
  public/assets/images/events/.gitkeep
  src/Controller/EventController.php
  src/Controller/HomeController.php
  src/Controller/MemberController.php
  src/Model/Address.php
  src/Model/AddressManager.php
  src/Model/Event.php
  src/Model/EventManager.php
  src/Model/Member.php
  src/Model/MemberManager.php
  src/View/Event/_form.html.twig
  src/View/Event/add.html.twig
  src/View/Event/events.html.twig
  src/View/Home/GymnasiumAdressSection.html.twig
  src/View/Home/about_us.twig
  src/View/Home/index.html.twig
  src/View/Member/memberForm.html.twig
Labels: Reviewed by PO

#31 Fix css footer
  composer.lock
  public/assets/css/styles.css
  public/assets/images/new_footer-aslo.png
  src/View/footer.html.twig
Labels: Reviewed by PO

#39 S3 us23 admin gallery
  .gitignore
  app/routing.php
  public/assets/css/adminGallery.css
  public/assets/images/1500x500.jpeg
  public/assets/images/gallery/.gitkeep
  public/assets/images/image5bc9971e6275a4.62562562.jpg
  public/assets/images/image5bc99a510edf41.33724827.jpg
  public/assets/images/image5bc99a511086f8.62492621.jpg
  public/assets/images/image5bc99a51118af8.61910824.jpg
  public/assets/images/image5bc99b58bf0a94.07565975.jpg
  public/assets/images/image5bc99b58c08843.66866385.jpg
  public/assets/images/image5bc99b58c16819.50295446.jpg
  public/assets/images/image5bc99b58c279a0.90679304.jpg
  public/assets/images/image5bc99de1c60694.48842372.jpg
  public/assets/images/image5bc99de1c7d345.28061929.jpg
  public/assets/images/image5bc9a02ce7bd30.00517429.jpg
  public/assets/images/image5bc9a2f276ce58.54652820.jpg
  src/Controller/PictureController.php
  src/Model/Picture.php
  src/Model/PictureManager.php
  src/View/Admin/adminPictureAdd.html.twig
Labels: Reviewed by PO, correction done

#43 S02 us08 presentation activity
  public/assets/css/styles.css
  public/assets/images/Aslotrain.jpg
  public/assets/images/ludosport.jpg
  src/View/Home/index.html.twig
  src/View/Home/presentationActivity.html.twig
Labels: Reviewed by PO

#47 S4 us33 admin list page
  app/routing.php
  public/assets/css/events.css
  public/assets/js/script.js
  src/Controller/EventController.php
  src/View/Event/list.html.twig
  src/View/layout.html.twig
Labels: Reviewed by PO

#37 Fix banniere
  public/assets/css/styles.css
  public/assets/images/banniere.jpg
  public/assets/images/banniere2.jpg
  public/assets/images/banniere45.jpg
  public/assets/images/banniere5.jpg
  public/assets/images/banniere69.jpg
  src/View/Home/banner.html.twig
  src/View/Home/index.html.twig
  src/View/header.html.twig
Labels: Reviewed by PO

#48 Dev
  .gitignore
  app/routing.php
  composer.lock
  public/assets/css/adminGallery.css
  public/assets/css/events.css
  public/assets/css/styles.css
  public/assets/images/1500x500.jpeg
  public/assets/images/Aslotrain.jpg
  public/assets/images/banniere.jpg
  public/assets/images/banniere2.jpg
  public/assets/images/banniere45.jpg
  public/assets/images/banniere5.jpg
  public/assets/images/banniere69.jpg
  public/assets/images/gallery/.gitkeep
  public/assets/images/image5bc9971e6275a4.62562562.jpg
  public/assets/images/image5bc99a510edf41.33724827.jpg
  public/assets/images/image5bc99a511086f8.62492621.jpg
  public/assets/images/image5bc99a51118af8.61910824.jpg
  public/assets/images/image5bc99b58bf0a94.07565975.jpg
  public/assets/images/image5bc99b58c08843.66866385.jpg
  public/assets/images/image5bc99b58c16819.50295446.jpg
  public/assets/images/image5bc99b58c279a0.90679304.jpg
  public/assets/images/image5bc99de1c60694.48842372.jpg
  public/assets/images/image5bc99de1c7d345.28061929.jpg
  public/assets/images/image5bc9a02ce7bd30.00517429.jpg
  public/assets/images/image5bc9a2f276ce58.54652820.jpg
  public/assets/images/ludosport.jpg
  public/assets/images/new_footer-aslo.png
  public/assets/js/script.js
  src/Controller/EventController.php
  src/Controller/PictureController.php
  src/Model/Picture.php
  src/Model/PictureManager.php
  src/View/Admin/adminPictureAdd.html.twig
  src/View/Event/list.html.twig
  src/View/Home/banner.html.twig
  src/View/Home/index.html.twig
  src/View/Home/presentationActivity.html.twig
  src/View/footer.html.twig
  src/View/header.html.twig
  src/View/layout.html.twig
Labels: Reviewed by PO

#49 S4_US32_display pictures on admin side
  .gitignore
  app/routing.php
  src/Controller/PictureController.php
  src/Model/PictureManager.php
  src/View/Admin/galerie.html.twig
Labels: Reviewed by PO
