Repository WildCodeSchool/orleans-0918-php-aslo, pull requests merged in 2018-11, with the labels that each got.

#53 fix routing
  app/routing.php
Labels: Reviewed by PO

#50 Fix navbar
  public/assets/css/styles.css
Labels: Reviewed by PO

#55 Fix PictureManager -> probleme de commentaire
  src/Model/PictureManager.php
Labels: Reviewed by PO, correction done

#57 Dev
  .gitignore
  app/routing.php
  public/assets/css/styles.css
  src/Controller/PictureController.php
  src/Model/PictureManager.php
  src/View/Admin/galerie.html.twig
Labels: Reviewed by PO

#46 Fix add event filter
  src/Controller/EventController.php
  src/View/Event/_form.html.twig
Labels: Reviewed by PO, correction done

#54 Us34 home pictures display
  public/assets/images/photo_galerie_1.png
  public/assets/images/photo_galerie_2.png
  public/assets/images/photo_galerie_3.png
  src/Controller/HomeController.php
  src/Model/PictureManager.php
  src/View/Home/galleryPhotosHome.html.twig
Labels: Reviewed by PO

#52 S5 us7 map
  composer.json
  composer.lock
  public/assets/css/styles.css
  public/assets/images/gymIcon.png
  public/assets/js/map.js
  src/Controller/HomeController.php
  src/Model/AddressManager.php
  src/View/Home/gymnasiumAdressSection.html.twig
  src/View/Home/index.html.twig
  src/View/layout.html.twig
Labels: correction done

#62 fix_dev_travisWarning_conformity
  src/Controller/EventController.php
  src/Controller/HomeController.php
  src/Controller/MemberController.php
  src/Controller/PictureController.php
  src/Model/EventManager.php
  src/Model/MemberManager.php
  src/Model/PictureManager.php
Labels: Reviewed by PO

#58 ajout des liens
  src/View/Home/about_us.twig
  src/View/Home/banner.html.twig
  src/View/footer.html.twig
  src/View/header.html.twig
Labels: Reviewed by PO

#60 S5 us35 admin page list
  src/View/Admin/adminPictureAdd.html.twig
  src/View/Admin/admin_layout.html.twig
  src/View/Admin/galerie.html.twig
  src/View/Admin/navAdmin.html.twig
Labels: Reviewed by PO

#59 S4_US31_AdminPictureDelete
  app/routing.php
  src/Controller/PictureController.php
  src/Model/PictureManager.php
  src/View/Admin/galerie.html.twig
Labels: Reviewed by PO

#51 S5 us27 admin events remove
  app/routing.php
  src/Controller/EventController.php
  src/Model/EventManager.php
  src/View/Event/list.html.twig
Labels: Reviewed by PO

#63 S05 us16 important event
  app/routing.php
  public/assets/css/events.css
  public/assets/css/styles.css
  src/Controller/EventController.php
  src/Controller/HomeController.php
  src/Model/Event.php
  src/Model/EventManager.php
  src/View/Event/list.html.twig
  src/View/Home/homeEvents.html.twig
  src/View/Home/index.html.twig
Labels: Reviewed by PO, correction done

#64 S5 us34 addres edit
  app/routing.php
  src/Controller/AddressController.php
  src/Controller/HomeController.php
  src/Model/AddressManager.php
  src/View/Home/_address_form.html.twig
Labels: Reviewed by PO, correction done

#67 Dev
  app/routing.php
  composer.json
  composer.lock
  public/assets/css/admin.css
  public/assets/css/events.css
  public/assets/css/styles.css
  public/assets/images/even.png
  public/assets/images/event_default.jpg
  public/assets/images/fond.png
  public/assets/images/gymIcon.png
  public/assets/images/odd.png
  public/assets/images/photo_galerie_1.png
  public/assets/images/photo_galerie_2.png
  public/assets/images/photo_galerie_3.png
  public/assets/js/map.js
  src/Controller/AddressController.php
  src/Controller/EventController.php
  src/Controller/HomeController.php
  src/Controller/ItemController.php
  src/Controller/MemberController.php
  src/Controller/PictureController.php
  src/Model/Address.php
  src/Model/AddressManager.php
  src/Model/Event.php
  src/Model/EventManager.php
  src/Model/MemberManager.php
  src/Model/PictureManager.php
  src/View/Admin/adminPictureAdd.html.twig
  src/View/Admin/admin_layout.html.twig
  src/View/Admin/galerie.html.twig
  src/View/Admin/navAdmin.html.twig
  src/View/Event/_form.html.twig
  src/View/Event/add.html.twig
  src/View/Event/events.html.twig
  src/View/Event/list.html.twig
  src/View/Home/_address_form.html.twig
  src/View/Home/about_us.twig
  src/View/Home/banner.html.twig
  src/View/Home/galleryPhotosHome.html.twig
  src/View/Home/gymnasiumAdressSection.html.twig
  src/View/Home/homeEvents.html.twig
  src/View/Home/index.html.twig
  src/View/footer.html.twig
  src/View/header.html.twig
  src/View/layout.html.twig
Labels: Reviewed by PO

#69 change layout -> admin_layout
  src/View/Home/_address_form.html.twig
Labels: Reviewed by PO

#70 fix css
  public/assets/css/events.css
  src/View/Event/list.html.twig
Labels: Reviewed by PO

#66 fix_style_galerieHome
  public/assets/css/styles.css
  src/View/Picture/index.html.twig
Labels: Reviewed by PO

#77 remove bgcolor
  public/assets/css/events.css
Labels: Reviewed by PO

#76 quick style adjustment
  public/assets/css/member.css
  src/View/Member/memberForm.html.twig
Labels: Reviewed by PO

#75 adjusment responsive on admin/galerie
  public/assets/css/styles.css
  src/View/Admin/galerie.html.twig
Labels: Reviewed by PO

#74 add padding on navAdmin
  src/View/Admin/admin_layout.html.twig
Labels: Reviewed by PO

#73 refonte page accueil
  public/assets/css/styles.css
  public/assets/images/stardust-1920x1080.png
  src/View/Home/about_us.twig
  src/View/Home/banner.html.twig
  src/View/Home/contact_form.twig
  src/View/Home/galleryPhotosHome.html.twig
  src/View/Home/gymnasiumAdressSection.html.twig
  src/View/Home/homeEvents.html.twig
  src/View/Home/index.html.twig
  src/View/Home/presentationActivity.html.twig
  src/View/Home/video.html.twig
  src/View/footer.html.twig
  src/View/layout.html.twig
Labels: Reviewed by PO, correction done

#79 fix de style
  public/assets/css/member.css
  public/assets/css/styles.css
  src/View/Event/list.html.twig
  src/View/Home/contact_form.twig
  src/View/Home/presentationActivity.html.twig
  src/View/Member/memberForm.html.twig
  src/View/footer.html.twig
Labels: Reviewed by PO

#78 PR dev to master final
  public/assets/css/events.css
  public/assets/css/member.css
  public/assets/css/styles.css
  public/assets/images/stardust-1920x1080.png
  src/View/Admin/admin_layout.html.twig
  src/View/Admin/galerie.html.twig
  src/View/Event/_form.html.twig
  src/View/Event/events.html.twig
  src/View/Event/list.html.twig
  src/View/Home/_address_form.html.twig
  src/View/Home/about_us.twig
  src/View/Home/banner.html.twig
  src/View/Home/contact_form.twig
  src/View/Home/galleryPhotosHome.html.twig
  src/View/Home/gymnasiumAdressSection.html.twig
  src/View/Home/homeEvents.html.twig
  src/View/Home/index.html.twig
  src/View/Home/presentationActivity.html.twig
  src/View/Home/video.html.twig
  src/View/Member/memberForm.html.twig
  src/View/Picture/index.html.twig
  src/View/footer.html.twig
  src/View/layout.html.twig
Labels: Reviewed by PO
